name: CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Code quality (Biome)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm (via npm)
        run: npm install -g pnpm@latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Run TypeScript Type Checking
        run: npx tsc

  deploy:
    name: Deploy to Vercel
    needs: type-check
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm (via npm)
        run: npm install -g pnpm@latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Deploy to Vercel
        run: pnpm dlx vercel@latest --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --name doctor-site-new
